Fix server-side error on API call
References:
https://www.prisma.io/docs/guides/other/troubleshooting-orm/help-articles/vercel-caching-issue

Fix the below from the Vercel log: https://vercel.com/sa4mi/frontend-shop-dao-generator-chainlink2023/logs?page=1&timeline=past30Minutes&startDate=1683988683765&endDate=1683990483765&selectedLogId=1683990377163521238103817293&selectedLogTimestamp=1683990377163&forceEndDate=1683990466918

```
Prisma has detected that this project was built on Vercel, which caches dependencies. This leads to an outdated Prisma Client because Prisma's auto-generation isn't triggered. To fix this, make sure to run the `prisma generate` command during the build process.

Learn how: https://pris.ly/d/vercel-build
PrismaClientInitializationError: Prisma has detected that this project was built on Vercel, which caches dependencies. This leads to an outdated Prisma Client because Prisma's auto-generation isn't triggered. To fix this, make sure to run the `prisma generate` command during the build process.

Learn how: https://pris.ly/d/vercel-build
    at Ba (/var/task/node_modules/@prisma/client/runtime/library.js:161:69)
    at new t (/var/task/node_modules/@prisma/client/runtime/library.js:174:3203)
    at 8869 (/var/task/.next/server/pages/api/accessTokenWalletAddress/create.js:21:33)
    at __webpack_require__ (/var/task/.next/server/webpack-api-runtime.js:25:42)
    at 5243 (/var/task/.next/server/pages/api/accessTokenWalletAddress/create.js:35:69)
    at __webpack_require__ (/var/task/.next/server/webpack-api-runtime.js:25:42)
    at __webpack_exec__ (/var/task/.next/server/pages/api/accessTokenWalletAddress/create.js:74:39)
    at /var/task/.next/server/pages/api/accessTokenWalletAddress/create.js:75:28
    at Object.<anonymous> (/var/task/.next/server/pages/api/accessTokenWalletAddress/create.js:78:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14) {
  clientVersion: '4.14.0',
  errorCode: undefined
}
RequestId: f9429795-2c00-4d0d-9600-d69324d41163 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```